# Generated by Django 3.0.5 on 2020-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('company', 'name')},
        ),
    ]
